server:
  port: 8001

spring:
  application:
    name: groundwater
  profiles:
    active: dev


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

